// Auto-generated by Orbit live preview — disables SSR to avoid Vite Node IPC issues
export default defineNuxtConfig({
  ssr: false,
  devServer: {
    host: '0.0.0.0',
  },
  vite: {
    server: {
      allowedHosts: true,
    },
  },
})
