import { describe, expect, it } from "vitest";
import { stripGeneratedDocArtifacts } from "./generated-doc";

describe("stripGeneratedDocArtifacts", () => {
  it("removes AI preamble before SDD heading", () => {
    const raw =
      "I'll explore the repository structure and key configuration files to build an accurate SDD from the codebase.\n\n" +
      "# System Design Document (SDD): Vesmon FE (project-bird-view)\n\n**Generated By:** Orbit";

    expect(stripGeneratedDocArtifacts(raw, "sdd")).toBe(
      "# System Design Document (SDD): Vesmon FE (project-bird-view)\n\n**Generated By:** Orbit"
    );
  });

  it("unwraps a markdown code fence around the document", () => {
    const raw =
      "```markdown\n# System Design Document (SDD): Demo\n\nBody\n```";

    expect(stripGeneratedDocArtifacts(raw, "sdd")).toBe(
      "# System Design Document (SDD): Demo\n\nBody"
    );
  });

  it("leaves content unchanged when it already starts with the heading", () => {
    const doc = "# Functional Specification Document (FSD): App\n\nDetails";
    expect(stripGeneratedDocArtifacts(doc, "fsd")).toBe(doc);
  });

  it("falls back to the first H1 when doc type is unknown", () => {
    const raw = "Starting analysis now.\n\n# Custom Title\n\nContent";
    expect(stripGeneratedDocArtifacts(raw)).toBe("# Custom Title\n\nContent");
  });

  it("strips preamble before PRD-style SRS headings", () => {
    const raw =
      "I'll analyze the repositories first.\n\n# Product Requirements Document (PRD) — MMS\n\nBody";
    expect(stripGeneratedDocArtifacts(raw, "srs")).toBe(
      "# Product Requirements Document (PRD) — MMS\n\nBody"
    );
  });

  it("strips preamble before first H2 when no H1 is present", () => {
    const raw = "I'll analyze the codebase first.\n\n## 1. Pendahuluan\n\nBody text.";
    expect(stripGeneratedDocArtifacts(raw)).toBe("## 1. Pendahuluan\n\nBody text.");
  });
});

describe("stripGeneratedDocArtifacts — JSON section payloads", () => {
  it("extracts markdown from multi-section JSON with preamble", () => {
    const raw =
      'I\'ll locate the existing product SDD and the per-repo design docs.\n' +
      'No product-root docs/SDD.md exists; emitting JSON patches.\n' +
      JSON.stringify({
        sections: [
          { heading: "## 1. Pendahuluan", content: "Intro text." },
          { heading: "## 2. Arsitektur", content: "Architecture details." },
        ],
      });
    const result = stripGeneratedDocArtifacts(raw, "sdd");
    expect(result).toContain("## 1. Pendahuluan");
    expect(result).toContain("Intro text.");
    expect(result).toContain("## 2. Arsitektur");
    expect(result).toContain("Architecture details.");
    expect(result).not.toContain("I'll locate");
    expect(result).not.toContain("No product-root");
  });

  it("extracts markdown from single-section JSON with H1 heading", () => {
    const raw =
      'Searching for the PRD file...\n' +
      JSON.stringify({
        heading: "# Product Requirements Document (PRD) — MMS",
        content: "## 1. Pendahuluan\n\nUpdated body.",
      });
    const result = stripGeneratedDocArtifacts(raw, "srs");
    expect(result).toBe("# Product Requirements Document (PRD) — MMS\n\n## 1. Pendahuluan\n\nUpdated body.");
  });

  it("leaves normal markdown unchanged when no JSON is present", () => {
    const doc = "# System Design Document (SDD)\n\n## 1. Pendahuluan\n\nReal content.";
    expect(stripGeneratedDocArtifacts(doc, "sdd")).toBe(doc);
  });
});
