import { describe, expect, it } from "vitest";
import { stripGeneratedDocArtifacts } from "./generated-doc";

describe("stripGeneratedDocArtifacts", () => {
  it("removes AI preamble before SDD heading", () => {
    const raw =
      "I'll explore the repository structure and key configuration files to build an accurate SDD from the codebase.\n\n" +
      "# System Design Document (SDD): Vesmon FE (project-bird-view)\n\n**Generated By:** Orbit";

    expect(stripGeneratedDocArtifacts(raw, "sdd")).toBe(
      "# System Design Document (SDD): Vesmon FE (project-bird-view)\n\n**Generated By:** Orbit"
    );
  });

  it("unwraps a markdown code fence around the document", () => {
    const raw =
      "```markdown\n# System Design Document (SDD): Demo\n\nBody\n```";

    expect(stripGeneratedDocArtifacts(raw, "sdd")).toBe(
      "# System Design Document (SDD): Demo\n\nBody"
    );
  });

  it("leaves content unchanged when it already starts with the heading", () => {
    const doc = "# Functional Specification Document (FSD): App\n\nDetails";
    expect(stripGeneratedDocArtifacts(doc, "fsd")).toBe(doc);
  });

  it("falls back to the first H1 when doc type is unknown", () => {
    const raw = "Starting analysis now.\n\n# Custom Title\n\nContent";
    expect(stripGeneratedDocArtifacts(raw)).toBe("# Custom Title\n\nContent");
  });
});
